Added implementation of some methods
ThePeoplesReserve/ccxt pull request #4
Opened 2021-02-25 18:49 UTC by dreamhostage

fetchOrders - some fixes;
fetchOpenOrders - some fixes;
fetchClosedOrders - added;
fetchStatus - added;
fetchCurrencies - added;

2021-03-03 10:51 UTC, akorunska requested changes

2021-03-03 10:51 UTC, akorunska commented on python/ccxt/tprexchange.py
> +    def fetch_status(self):
Did you add implementation right to this file? Because from the warning above it seems like it is supposed to be generated:
https://github.com/ThePeoplesReserve/ccxt/blob/ca3432e23263c86ba7acae258f2b332c032c8d54/python/ccxt/tprexchange.py#L3

2021-03-03 10:51 UTC, akorunska commented on python/ccxt/tprexchange.py
> +                return json.loads("""{"status": "ok"}""")
Is there any reason to use triple quotes? They are usually used as docstrings or as multiline strings. See https://www.tutorialspoint.com/triple-quotes-in-python

2021-03-03 10:51 UTC, akorunska commented on python/ccxt/tprexchange.py
> +            return response
The structure you return from this method is absolutely the same as the original one. However, fetch_currencies is part of ccxt public API (see https://github.com/ccxt/ccxt/wiki/Manual#overview) and the response should be formatted properly to meet ccxt standart. 
I believe, this is how each currency data should be formatted: https://github.com/ccxt/ccxt/wiki/Manual#currency-structure

2021-03-03 10:51 UTC, akorunska commented on python/ccxt/tprexchange.py
> +            limit = 100
Where does 100 come from? Is it some kind of default limit?
And why do we need to replace zero values with some sort of empty constants in the first place?

2021-03-03 10:51 UTC, akorunska commented on python/ccxt/tprexchange.py
> +        return self.privatePostExchangeOrderTrades(request)
Where is the implementation of this private method? And do i understand correctly that that trades will not be reformatted under ccxt standard? https://github.com/ccxt/ccxt/wiki/Manual#order-structure

2021-03-03 10:51 UTC, akorunska commented on python/ccxt/tprexchange.py
> +        return self.privatePostExchangeOrderMyTrades()
Where is the implementation of this private method? And do i understand correctly that that trades will not be reformatted under ccxt standard? https://github.com/ccxt/ccxt/wiki/Manual#order-structure

2021-03-03 13:28 UTC, dreamhostage commented on python/ccxt/tprexchange.py
> +                return json.loads("""{"status": "ok"}""")
It was made for quick converting string to python dict for informative responses. I couldn't find another ways...

2021-03-03 13:34 UTC, dreamhostage commented on python/ccxt/tprexchange.py
> +            limit = 100
Limit changed to 20 the same as default value on backend. We need to replace zero values bacause if this values will be like None here (as a default) we will have an error on exchange backend because it is not able to treat this situation.

2021-03-03 14:04 UTC, dreamhostage commented on python/ccxt/tprexchange.py
> +    def fetch_status(self):
Will be discussed on meeting.

2021-03-03 14:06 UTC, akorunska commented on python/ccxt/tprexchange.py
> +                return json.loads("""{"status": "ok"}""")
Why would you want to convert string to a python dict? How about returning dict right away without joading it from json?
I believe `return {'status': 'ok'}` will do exactly the same, yet it's way more simple.

2021-03-03 14:07 UTC, akorunska commented on python/ccxt/tprexchange.py
> +                return json.loads("""{"status": "ok"}""")
You can learn more about instantiating dictionaries in basic python tutorials https://www.w3schools.com/python/python_dictionaries.asp

2021-03-03 14:10 UTC, akorunska commented on python/ccxt/tprexchange.py
> +            limit = 100
Is the thing with our exchange back end not being able to handle null values fixable?
Anyway, let's move 100 to some kind of informative constant, because now it's highly confusing when reading the code.

2021-03-04 14:42 UTC, dreamhostage commented on python/ccxt/tprexchange.py
> +                return json.loads("""{"status": "ok"}""")
fixed

2021-03-04 14:48 UTC, dreamhostage commented on python/ccxt/tprexchange.py
> +            limit = 100
fixed

2021-03-05 11:35 UTC, akorunska commented on python/ccxt/tprexchange.py
> +        limit_const = 20
It's the matter of taste, but i'd rather call it "default_order_amount_limit" or something like that

2021-03-05 11:37 UTC, akorunska commented on python/ccxt/tprexchange.py
> +            limit = limit_const
This piece of code is duplicated several times. Would be nice to refactor without duplication

2021-03-05 11:38 UTC, akorunska approved these changes

2021-03-05 12:16 UTC, dreamhostage commented on python/ccxt/tprexchange.py
> +            return response
fixed

2021-03-05 12:18 UTC, dreamhostage commented on python/ccxt/tprexchange.py
> +        return self.privatePostExchangeOrderMyTrades()
fixed

2021-03-05 12:18 UTC, dreamhostage commented on python/ccxt/tprexchange.py
> +        return self.privatePostExchangeOrderTrades(request)
fixed

2021-03-05 14:45 UTC, dreamhostage commented on python/ccxt/tprexchange.py
> +        limit_const = 20
fixed

2021-03-12 11:13 UTC, DancingAxolotl approved these changes

2021-03-12 12:47 UTC, merged